In [ ]:
# Basic Of tensorflow 
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.5MB 52kB/s 
     |████████████████████████████████| 51kB 5.1MB/s 
     |████████████████████████████████| 3.0MB 39.2MB/s 
     |████████████████████████████████| 419kB 31.1MB/s 


In [ ]:
import tensorflow as tf

import numpy as np



In [ ]:
tensorCon=tf.constant([[23,45],[34,67]])#MAKING A tensor which is constant
tensorCon

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23, 45],
       [34, 67]], dtype=int32)>

In [ ]:
tensorCon.shape #showing the shape 

TensorShape([2, 2])

In [ ]:
tensorCon.numpy() # showing all the tensor values 


array([[23, 45],
       [34, 67]], dtype=int32)

In [ ]:
#converting numpy array to tensor 
numpy_array=np.array([[12,34],[23,12]])

conversion=tf.constant([numpy_array])
conversion

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[12, 34],
        [23, 12]]], dtype=int32)>

In [ ]:
 # operation with tensor 
 # addition 
 tensor=tf.constant([[1,4],[2,5]])
 tensor 



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5]], dtype=int32)>

In [ ]:
mult=tensor*5
mult

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 20],
       [10, 25]], dtype=int32)>

In [ ]:
# the same with addition subtration and division
div=tensor/2
div

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 2. ],
       [1. , 2.5]])>

In [ ]:
#find the square 
sq=np.square(tensor)
sq

array([[ 1, 16],
       [ 4, 25]], dtype=int32)

In [ ]:
#find the square root 
sqroot=np.sqrt(tensor)
sqroot

array([[1.        , 2.        ],
       [1.41421356, 2.23606798]])

In [ ]:
# dot product btween two tensor 
tensor1=tf.constant([[3,4],[5,7]])
tensor2=tf.constant([[5,6],[6,9]])
dotprodct=np.dot(tensor1,tensor2)
dotprodct

array([[39, 54],
       [67, 93]], dtype=int32)

In [ ]:
# tensorflow string

tensoString=tf.constant("Arshad khan")
tensoString

<tf.Tensor: shape=(), dtype=string, numpy=b'Arshad khan'>

In [ ]:
# tensorFlow Array of strings 
tensorArray=tf.constant(["AI","ML","DL"])
tensorArray

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'AI', b'ML', b'DL'], dtype=object)>